//
//  TitleCustomizationView.swift
//  impressionsv1
//
//  Created by Hardik Golchha on 07/02/26.
//

import SwiftUI

struct TitleCustomizationView: View {
    @ObservedObject var coordinator: CreateImpressionCoordinator
    @FocusState private var isEditing: Bool
    @State private var titleText: String = ""
    
    // Auto-generated title from coordinator data
    private var autoGeneratedTitle: String {
        coordinator.data.title.isEmpty ? generateTitle() : coordinator.data.title
    }
    
    private func generateTitle() -> String {
        if let place = coordinator.data.place,
           let meal = coordinator.data.meal {
            let companionText = coordinator.data.companions.first?.rawValue.lowercased() ?? "friends"
            return "\(meal.rawValue) with \(companionText) at \(place.name), \(place.location ?? "")"
        }
        return ""
    }
    
    var body: some View {
        ZStack {
            Color.appBackground
                .ignoresSafeArea()
            
            VStack(spacing: 0) {
                // Header Section
                HStack {
                    // Back button
                    Button(action: {
                        coordinator.goBack()
                    }) {
                        Image(systemName: "chevron.left")
                            .font(.system(size: 18, weight: .semibold))
                            .foregroundColor(.textPrimary)
                            .frame(width: 44, height: 44)
                    }
                    
                    Spacer()
                    
                    // Title
                    Text("Give it a title")
                        .font(AppFont.title2)
                        .foregroundColor(.textPrimary)
                    
                    Spacer()
                    
                    // Balance spacing
                    Color.clear
                        .frame(width: 44, height: 44)
                }
                .padding(.horizontal, Spacing.md)
                .padding(.top, Spacing.xs)
                
                // Title Card - Centered vertically
                Spacer()
                
                VStack(spacing: Spacing.sm) {
                    // Title Card - Compact badge style
                    TextField("", text: $titleText, axis: .vertical)
                        .font(AppFont.title3)
                        .foregroundColor(.textPrimary)
                        .multilineTextAlignment(isEditing ? .leading : .center)
                        .lineLimit(3)
                        .focused($isEditing)
                        .textFieldStyle(.plain)
                        .fixedSize(horizontal: false, vertical: true)
                        .padding(.vertical, Spacing.sm)
                        .padding(.horizontal, Spacing.md)
                        .background(
                            RoundedRectangle(cornerRadius: CornerRadius.large)
                                .fill(Color.cardBackground)
                        )
                        .padding(.horizontal, Spacing.md)
                        .contentShape(Rectangle())
                        .onTapGesture {
                            if !isEditing {
                                isEditing = true
                            }
                        }
                    
                    // Helper Text
                    Text("Tap to edit")
                        .font(AppFont.caption)
                        .foregroundColor(.textTertiary)
                        .opacity(isEditing ? 0 : 1)
                        .animation(.easeInOut(duration: 0.2), value: isEditing)
                }
                
                Spacer()
                
                // Continue Button
                VStack {
                    Button(action: {
                        coordinator.completeTitle(title: titleText)
                    }) {
                        Text("Continue")
                            .frame(maxWidth: .infinity)
                    }
                    .primaryButton()
                    .padding(.horizontal, Spacing.md)
                    .padding(.bottom, Spacing.md)
                }
                .background(Color.appBackground)
            }
        }
        .navigationBarHidden(true)
        .onTapGesture {
            // Dismiss keyboard when tapping outside card
            if isEditing {
                isEditing = false
            }
        }
        .onAppear {
            // Auto-generate title on load
            if titleText.isEmpty {
                titleText = autoGeneratedTitle
            }
        }
        .toolbar {
            ToolbarItemGroup(placement: .keyboard) {
                Spacer()
                Button("Done") {
                    isEditing = false
                }
                .foregroundColor(.textPrimary)
            }
        }
    }
}

#Preview {
    TitleCustomizationView(coordinator: CreateImpressionCoordinator())
}
